trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- template: templates/gitleaks-scan.yaml
  parameters:
    scanLocation: $(Build.SourcesDirectory)
    configPath: $(Build.SourcesDirectory)/configuration/gitleaks.toml
